services:
  - type: web
    name: chirag-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: static_site
    name: chirag-frontend
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: static_site
    name: chirag-cms
    plan: starter
    rootDir: cms
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ckb-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
